# Serveur
server.port=8080

# H2
spring.datasource.url=jdbc:h2:mem:tierzendb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Console H2 (utile pour vérifier en dev)
spring.h2.console.enabled=true
